server:
  port: 0

spring:
  application:
    name: global-config

  profiles:
    active: default

  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false

logging:
  level:
    root: INFO
