server:
  port: 8088

spring:
  application:
    name: ms-authentication
  data:
    mongodb:
      uri: mongodb://localhost:27017/authbd
      
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

key_encriptacion: BOOTCAMO592025jd
key_token: lAwz5Rw8QXbEuuHTW8uJbw==
jwt_token_duration_segundos: 3600000
jwt_refresh_token_duration_segundos: 3900
