server:
  port: 8088

spring:
  application:
    name: ms-authentication
  data:
    mongodb:
      uri: mongodb://localhost:27017/authbd
      
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

key_encriptacion: BOOTCAMO592025jd
key_token: aR2F8FZQF6b2K8nR5HXpzz0LRq3xZbxX/9Skkl6P94U=
jwt_token_duration_segundos: 3600000
jwt_refresh_token_duration_segundos: 3900
