server:
  port: 8081

spring:
  application:
    name: ms-customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/custmersdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088
logging:
  level:
    root: INFO
