server:
  port: 8083

spring:
  application:
    name: ms-credits
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      #defaultZone: http://ms-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    root: INFO
