server:
  port: 8080

spring:
  application:
    name: ms-gateway 
    
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**

        - id: ms-accounts
          uri: http://localhost:8082
          predicates:
            - Path=/v1.0/accounts/**

        - id: ms-credits
          uri: http://localhost:8083
          predicates:
            - Path=/v1.0/credits/**

        - id: ms-transactions
          uri: http://localhost:8084
          predicates:
            - Path=/v1.0/transactions/**

        - id: ms-authentication
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/auth/** 

key_token: lAwz5Rw8QXbEuuHTW8uJbw==
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8088/api/v1/auth
