server:
  port: 8086

spring:
  application:
    name: ms-yanki
  data:
    mongodb:
      uri: mongodb://localhost:27017/yankidb
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      transaction: "yanki-transactions"
 
logging:
  level:
    root: INFO

